version: '3'
services:
  db:
    container_name: postgres
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=receitas
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data